name: garment_productivity_prediction
channels:
  - conda-forge
dependencies:
  - python=3.10
  - flake8
  - jupyter
  - jupyterlab
  - ipython
  - pip
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - pip:
      - black
      - nbqa
      - flake8
